### ISSUE TITLE
Please translate to english

### ISSUE THREAD

**Issue by Ahmed-Eldalatony** [eightHundreds/obsidian-dida-sync#11]

**Comment by eightHundreds** [comment]
did you mean readme.md？

**Comment by AlJohri** [comment]
thanks for creating this plugin @eightHundreds!

would you mind clarifying in one or two sentences at the top of [README.EN.md](https://github.com/eightHundreds/obsidian-dida-sync/blob/master/README.EN.md) what this plugin does more specifically? is it one way sync or two way sync? does it sync on a schedule or does is it only by running the given command? also in the Configuration section it says "filter out the content under the specified list" or "Filter out content containing specified tags"-- it was unclear if this means filtering that list / tag _out_ (i.e. get all todos except this tag) or filtering in (only get todos from this list)

p.s. what does `dida` mean?

**Comment by eightHundreds** [comment]
`dida` is the pinyin of the Chinese name of this product
