### ISSUE TITLE
同步不成功 显示返回 401

### ISSUE THREAD

**Issue by bambooom** [eightHundreds/obsidian-dida-sync#14]
按照文档设置之后，进行同步时，发现 notification 显示返回 401，同步不成功。
![Screenshot 2023-09-16 at 22 41 29](https://github.com/eightHundreds/obsidian-dida-sync/assets/14840170/935f0ee5-eb39-4fac-a6d4-ebe0f72270e5)

如果 Toggle Developer Tools，还有以下报错：

![Screenshot 2023-09-16 at 22 40 17](https://github.com/eightHundreds/obsidian-dida-sync/assets/14840170/0947e68c-4807-490f-b3ed-e4a36a06b47b)

请问是否有办法能修复？感谢！

**Comment by eightHundreds** [comment]
有没有可能是你的账号密码错误? 我这边还是能用

**Comment by bambooom** [comment]
@eightHundreds 我终于发现问题了，是因为我在 front matter 里写成了 dida，但我用的其实是 ticktick。。。😂
不好意思麻烦了，谢谢！
