### ISSUE TITLE
无法得到指定project的任务列表

### ISSUE THREAD

**Issue by niecailong** [eightHundreds/obsidian-dida-sync#15]
![image](https://github.com/eightHundreds/obsidian-dida-sync/assets/75868761/44b838dc-1acd-480d-91dc-72761823dd88)
同步后，得到的还是dida清单里全部的任务列表清单。

**Comment by eightHundreds** [comment]
把`dida` 去掉, 我后面优化下

**Comment by kingrach** [comment]
Works for me as of today when my Properties are like this:

---
ticktick:
  projectId: xxx
  status: uncompleted
---

Thank you! :D

**Comment by eightHundreds** [comment]
fixed in 1.7.2
