### ISSUE TITLE
同步没有生效!

### ISSUE THREAD

**Issue by musicleaf** [eightHundreds/obsidian-dida-sync#18]
<img width="458" alt="image" src="https://github.com/eightHundreds/obsidian-dida-sync/assets/35360006/d4025b3c-4258-4311-866c-c99ff5257baa">

**Comment by eightHundreds** [comment]
boolean类型,不是字符串类型

**Comment by musicleaf** [comment]
> boolean类型,不是字符串类型. 用勾选框

原来是这样,搞定.
