### ISSUE TITLE
Thank You So much for this plugin!

### ISSUE THREAD

**Issue by connradolisboa** [eightHundreds/obsidian-dida-sync#22]
Just want to thank you for this amazing plugin! 
the possibilities are incredible. I choosed TickTick because of the sticky notes feature for doing research. I was a bum to have to manually copy and paste the notes. Now with a proper workflow I can do this and much more!

**Comment by eightHundreds** [comment]
Thank you for your thank you, you are the first to thank me, others will only make demands on me :(
