### ISSUE TITLE
目前同步内容支持的方面？

### ISSUE THREAD

**Issue by yoghurtdewdew** [eightHundreds/obsidian-dida-sync#3]
大佬您好！

请问目前是否支持同步任务详情？以及任务中的图片和附件？目前已知滴答清单的那个图片除了一个一个复制出来没其他方法弄出来，所以我一直都祈祷这个公司好好活着别倒了，不知道大佬这边对于图片搞出来有啥好办法？我看到他们那个图片在任务详情中其实是markdown链接，但是这个链接放到其他地方是完全用不了的😂

同步的任务是否可以支持一下带上滴答清单的任务链接？比如，http多少多少的那个任务链接，为了关联起来，自己一条一条复制还蛮累的，或者带上个url scheme能在桌面应用中打开也蛮好！

**Comment by eightHundreds** [comment]
安排

**Comment by eightHundreds** [comment]
顺便问下, 这个项目为什么最近几周很多人star

**Comment by quanru** [comment]
> 顺便问下, 这个项目为什么最近几周很多人star

我猜是因为这个 Twitter！让大家知道了这个插件：https://twitter.com/geekbb/status/1678933097054871552?t=yy43BYh8gB3nlGvQY2_4Sw&s=19

**Comment by eightHundreds** [comment]
我已经发布了

**Comment by eightHundreds** [comment]
插件名称我换了，需要重新安装
