### ISSUE TITLE
Should it work with ticktick.com or only the chinese version?

### ISSUE THREAD

**Issue by machado-t** [eightHundreds/obsidian-dida-sync#7]
I'm trying to sync my ticktick account but i'm getting "Sync failed Request failed, Status 401".

**Comment by eightHundreds** [comment]
username or password wrong

**Comment by eightHundreds** [comment]
Make sure you can log in with your account and password here
https://ticktick.com/signin

**Comment by eightHundreds** [comment]
you should add 

```
---
ticktick: true
---
```

in front of you markdown, not `dida`

**Comment by machado-t** [comment]
That was it. Thank you very much
