### ISSUE TITLE
现在能和ticktick（国际版）进行同步吗

### ISSUE THREAD

**Issue by calmwaves111** [eightHundreds/obsidian-dida-sync#8]
目前是否支持ticktick呢，如果支持，设置界面里没有可选项来选择滴答清单和ticktick
我有两个账号，一个是滴答清单，一个是ticktick，但是这两个账号的账号和密码都是一样的，所以我不知道该如何让我登录到ticktick而不是滴答清单

**Comment by eightHundreds** [comment]
看英文文档

**Comment by calmwaves111** [comment]
> 看英文版README

谢谢你耐心回复，确实可以和ticktick同步，是我之前没有仔细看readme。
十分感谢你开发这个插件，这对我使用obsidian和ticktick都很有用
